static const char javascript[] PROGMEM = " $(document).ready(function(){\r\n"
            " $('#wheel').draggable({handle: '.ui-rotatable-handle'}).rotatable({ "
            "    rotate: function(e, ui){ "
            "    var degrees = ui.angle.current * 180/Math.PI; "
            "    if ( degrees > 90 ) {    "
            "       ui.angle.current = Math.PI/2;    "
            "    } else if ( degrees < -90) {        "
            "       ui.angle.current = -1*Math.PI/2;  "
            "    } "
            "    degrees = degrees + 90; "
            "    console.log(degrees); "
            "    var s = String(degrees); "
            " $.ajax({ "
            "    type: 'POST', "
            "    url: 'dataHandler', "
            "    data: s, "
            "    contentType: 'application/x-www-form-urlencoded' "
            " }); "
            "},snap: true " 
            "});"
            "});";
