static const char page[] PROGMEM = "<head>"
            " <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
            " <script src='https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'></script> "
            " <script type='text/javascript' src='http://code.jquery.com/ui/1.11.4/jquery-ui.js'></script> "
            " <script type='text/javascript' src='https://www.jqueryscript.net/demo/jQuery-UI-Rotatable-Elements/jquery.ui.rotatable.js'></script> "
            " <script src='https://cdnjs.cloudflare.com/ajax/libs/jqueryui-touch-punch/0.2.3/jquery.ui.touch-punch.min.js'></script>"
            " <script src='https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js'></script>"
            " <script type='text/javascript' src='jscript.js'></script> "
            " <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css'>"
            " <style> "
            " #wheel { "
            "  width: 200px; "
            "  height: 200px; "
            "  margin-left: 25%; "
            "  margin-top: 20%; "
            " } "
            " .ui-rotatable-handle { "
            "   height: 200px; "
            "   width: 200px; "
            "   cursor: pointer; "
            "   background-image: url(https://i.imgur.com/5Wh9Ym0.png); "
            "   background-size: 100%; "
            " } "
            " #tmm-logo { "
            "   width: 50%; "
            "   margin-top: 20%; "
            " } "
            " </style> "
            " </head>"
            " <body>"
            " <div class='container'> "
            "  <h1>WeMos D1 Servo Controller</h1> "
            "  <h4>Rotate wheel to rotate servo</h4>"
            "  <a href='https://www.teachmemicro.com/wemos-d1-mini-servo-controller'>Full tutorial</a>"
            "  <div class='row'> "
            "   <div class='col-xs-12'> "
            "    <div id='wheel'></div> "
            "   </div> "
            "   <div class='col-xs-12'> "
            "     <img id='tmm-logo' src='https://i.imgur.com/G80eVhL.png' /> "
            "   </div>"
            "  </div> "
            " </div> "
            "</body>";
